### ISSUE TITLE
Tag a release?

### ISSUE THREAD

**Issue by joehuchette** [mtanneau/MathOptPresolve.jl#19]
Is it time?

**Comment by mtanneau** [comment]
There's obviously a lot we can improve on, but I guess we have the bare minimum for tagging, yes.

**Comment by joehuchette** [comment]
@mtanneau I think you might need to install the registrator app for this repo (it doesn't appear that I have permissions): https://github.com/JuliaRegistries/Registrator.jl

**Comment by mtanneau** [comment]
Done! Thanks

**Comment by mtanneau** [comment]
Pointer: #22 we had compat entries in `test/Project.toml` but not in `/Project.toml`.

The Julia compat entry is at `1.5`. If there's a good reason to support Julia1.0 it should be possible, but it will require some changes to the code.

**Comment by joehuchette** [comment]
Let's just do 1.5 then

**Comment by mtanneau** [comment]
Closed by https://github.com/JuliaRegistries/General/pull/30920
